#!/bin/bash

function _install {
	command -v boot-repair && return || \
	install ppa:yannubuntu/boot-repair -y
	install update
	install boot-repair -y
}

function _process {
	_install && \
	boot-repair
}

_process

