#!/bin/bash
# Version - 1.0.0 - rc

file="$1"
comm="${@:2}"

function use {
	usage $0 'file [commands for each line]' "${comm}" || exit -1
}


if [ ! -f "$file" ]; then
    echo "File not found"
    comm=''
fi
    
use

while IFS='' read -r line || [[ -n "$line" ]]; do
	#echo line - $line
	$( echo "${comm}" | sed "s|this|$line|g"  )
done < "$file"

