#!/bin/bash
# Version - 1.0.0 - rc

file="$1"
comm="${@:2}"

usage $0 'file [commands for each line]' "${comm}" || exit -1

while IFS='' read -r line || [[ -n "$line" ]]; do
	$( echo ${comm} | sed "s/this/$line/g" )
done < "$file"

