#!/bin/bash
# Version - 1.0.0 - rc

cn="$1" 
ks="$2"

pd='Program to generate a certificate key, and certificate signing request'

usage $0 '[cn] [keysize - default 4096]' "${cn}" "${pd}" || exit 1

echo Generating certificate - CN - ${cn} ...

openssl req -new -newkey rsa:${ks} -nodes -keyout ${cn}.key -out ${cn}.csr

