#!/bin/bash
# Version - 1.0.0 - rc

stuff=`readarg $1`

function use {
	usage $0 hexadecimal $st || exit 0
}

function convert {
	echo "obase=10;ibase=16;${stuff}" | bc
}

st=$stuff && use || exit 1
st=
checkhexadecimal $stuff || use || exit 0
stuff=`touppercase $stuff`
convert

