#!/bin/bash
# Version - 1.0.0 - rc 

supported=ubuntu
checksupport=`whatlinuxflavour | egrep -io ubuntu`
if [ -z "$checksupport" ] ; then echo only supported on $supported && exit 0 ; fi
sudo dpkg --add-architecture i386
sudo apt-add-repository 'https://dl.winehq.org/wine-builds/ubuntu/'
#sudo add-apt-repository ppa:ricotz/unstable
wget https://dl.winehq.org/wine-builds/Release.key | sudo apt-key add - 
wget https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
#sudo add-apt-repository ppa:ubuntu-wine/ppa
install upgrade
#install winehq-stable
install --install-recommends wine-staging
install winetricks
