#!/bin/bash
# Version 2.0.0

inst=install

installcheck $0 $1 || exit 1

function _osinst {
	olog "$0 ${inst}ing $ty ${*}"
	${ty}${inst} ${*} 
	#&&\
	#'olog ${*} successful ✓
}

function _process {
	olog $0
	ty=`isdebrpm`
	exceptions=( docker veracrypt brew dbeaver chrome opera )
	exc=$( echo ${exceptions[*]} | tr ' ' '|' )
	if regexcheck "^($exc)$" "$1" ; then 
		olog $0 $1
		install$1
	elif regexcheck "(kvm|qemu|virt)" $1 ; then
		installkvm
	elif regexcheck "mac|rpm|deb" "$ty" ; then _osinst ${*}
	elif showlinuxflavour | grep -i alpine ; then alpineinstall ${*}
	else errexit "$0 - unknown OS type - $ty - can not install $1" ||\
		exit 1
	fi || exit 1

}

_process ${*} || exit 1

