#!/bin/bash
# Version - 1.0.0 - rc

pr="$1"
st="$2"

usage $0 '$0 [integer parameter to check]' "$pr" || exit 1

function use {
	#olog "$1 - $2"
	usage "$1" 'integer' "$2" || exit 1
}

[  "$st" ] || $use "$pr" "$st" || exit 1 && \
isinteger "$st" && exit 0 || use "$pr" '' || exit 1
