#!/bin/bash
# Requires - sshfs

#sshfs -V | grep -o version > /dev/null && echo yes || install sshfs -y

osudo groupadd fuse
osudo usermod -a -G fuse $USER

function sshfsf {
	mkdir -p $dest
	sshfs -o allow_other $src $dest
}

function checkhome {
	olog $0 checking if home
	stu=`echo $src | cut -d: -f1 | totitlecase`
	#olog stu - $stu
	ff=`echo $src | cut -d: -f2-`
	getwakedevs | grep -io $stu || \
		return && amiathome && echo "$0 at home" || errexit "$0 not at home" || src="${stu}:${ff}"
}


sshfsex="`command -v sshfs`"

if [ -z "$sshfsex" ];  then
	echo sshfs needs to be installed
	exit -1
fi

src=$1
dest=$2

if [ -z "$dest" ] ; then
	fin=`echo $src | cut -d':' -f1 `
	echo fin - $fin 

	dest="`getomnt`${fin}"
fi

checkhome

echo $src - $dest

usage $0 'source destination' "${dest}" 'Tool to mount via sshfs the remote source onto the local destination folder' || exit -1

sshfsf

#echo beep

