#!/bin/bash
# Requires - sshfs

#sshfs -V | grep -o version > /dev/null && echo yes || install sshfs -y

osudo groupadd fuse
osudo usermod -a -G fuse $USER

function sshfsf {
	mkdir -p $dest
	sshfs -o allow_other $src $dest
}

sshfsex="`command -v sshfs`"

if [ -z "$sshfsex" ];  then
	echo sshfs needs to be installed
	exit -1
fi

src=$1
dest=$2

if [ -z "$dest" ] ; then
	fin=`echo $src | cut -d':' -f1 `
	echo fin - $fin 

	dest="`getomnt`${fin}"
fi

echo $src - $dest

usage $0 'source destination' "${dest}" 'Tool to mount via sshfs the remote source onto the local destination folder' || exit -1

sshfsf

#echo beep

