#!/bin/bash
# Version - 1.0.0 - rc 

netw=`readarg "${*}"`

usage $0 '[network address/network mask prefix]' "${netw}" 'Please note - MAC addresses available if run with sudo access' || exit 1

dat=`date +%Y%m%d%H%M%S` 

onmap -sn ${netw} | egrep -v 'Host is up' | sed ':a;N;$!ba;s/\nMAC Address: /,/g' | egrep -v 'Starting ' | egrep -v 'Nmap done: ' | sed 's/Nmap scan report for //g' | sed 's/ (/,"(/g' | sed 's/)$/)"/g' | sed "s/\$/,${dat}/"

