#!/bin/bash
# Dropbox Wrapper
# Version - 1.0.0 - rc

function all {
	dropbox status > /dev/null || install https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb
}

function restart {
	dropbox stop
       dropbox start
}

all 

if [ "restart" = "$1" ] ; then 
	restart
elif [ "status" = "$1" ] ;then
	echo The Dropbox status is...
	dropbox status
else 
	dropbox "${*}"
fi

#dropbox status

