#!/bin/bash
# Version - 1.0.0 - rc

stuff=`readarg "${*}"`

stu=`echo $stuff | cut -d' ' -f1`

usage $0 'program to use or install then use' $stu  || exit 1

command -v ${stu} && echo $stu is installed || install ${stu}

${stuff}

