#!/bin/bash
# Script to regex pattern check strings
# Version - 1.0.0 - rc

function use {
	desc='regex checks the string, and will output the string if complies. Exits 1 if not.'
	usage $0 "regex string_to_check" "${stuff}" "${desc}" || errexit "Bad input" || exit 1
}

function check {
	if [ "$stuff" ] && [[ $stuff =~ ${regex} ]];then
		olog $stuff
	else
		exit 1
	fi

}

regex=$1
stuff=$2

use
check

