#!/bin/bash
# Version - 1.0.0 - rc

pd='Program to encode or decode the string'

fn=''
string=''

function use {
	echo $1
	usage $0 'en|de string' "$string" "$pd" || exit 1
}

fn=`regexcheck "(en|de)" "${1}" && echo "$1" || use 'please state en or de for encode or decode'`
string="${@:2}"

use ''

function urlencode {
    # urlencode <string>

    local length="${#1}"
    for (( i = 0; i < length; i++ )); do
        local c="${1:i:1}"
        case $c in
            [a-zA-Z0-9.~_-]) printf "$c" ;;
            *) printf '%s' "$c" | xxd -p -c1 |
                   while read c; do printf '%%%s' "$c"; done ;;
        esac
    done
}

function urldecode {
    # urldecode <string>

    local url_encoded="${1//+/ }"
    printf '%b' "${url_encoded//%/\\x}"
}

"url${fn}code" "${string}"

