#!/bin/bash
# Version - 1.0.0 - rc

pd='Program to encode or decode the string'

fn=''
string=''
regchk="(en|de)"

function use {
	usage $0 'en|de string' "$string" "$pd" || exit 1
}

fn=`regexcheck ${regchk} "${1}" && echo "$1" || use 'please state en or de for encode or decode'`
string="${@:2}"

fn=`echo $fn | cut -d' ' -f1`

use ''

comm="url${fn}code"

$comm "${string}" || errexit "$0 Unable to $comm $string" || exit 1

