#!/bin/bash
# Version - 1.0.0 - rc

/usr/local/bin/getpath

bas=$1
#echo - 1 - $bas
par=$3
#echo - 3 - $par
usage=$2
#echo - 2 - $usage
extra=$4

if [ -z "$usage" ]; then 
	echo Usage of usage:
	echo "$BASENAME $0 \$BASENAME \$0 [usage post script] [parameter to check]"
	exit 1
fi


if [ -z "$par" ];then
	printf "${extra}"  && printf '\n\n'
	echo Usage:
	echo "${bas} ${usage}"
	exit 1
else
	exit 0
fi
