#!/bin/bash
# Version - 1.0.0 - rc

#/usr/local/bin/getpath

bas=$1
par=$3
usage=$2
extra=$4

if [ -z "$usage" ]; then 
	echo Usage of usage:
	echo "$BASENAME $0 \$BASENAME \$0 [usage post script] [parameter to check]"
	exit 1
fi


if [ -z "$par" ];then
	[ "$extra" ] && printf "${extra}\n\n" 
	echo Usage:
	echo "${bas} ${usage}"
	exit 1
else
	exit 0
fi
