#!/bin/bash
# Version - 1.0.0 - rc

ismac && echo mac && exit 0

supported="ubuntu|xenial|focal|bionic|trusty|alpine|oracle|centos|PRODUCT_VERSION=\"7\"|rocky|debian|buster|bullseye"
#for i in `cat /etc/*release | egrep -io ${supported}`;do echo $i | tolowercase ;done | sort -u
cat /etc/*release | egrep -io ${supported} | sort -uf | tr '\n' ' ' | tolowercase

